### PR TITLE
Version 3.0.0

### PR DESCRIPTION
**Pull request by alvir**
Upgrade major version through dbf version to 4.0 and broken support of 2.3 Ruby

### CODE REVIEW

**Comment by keithdoggett** [comment]
Thanks for submitting this! Should get this released soon.

**Comment by alvir** [comment]
@keithdoggett Probably we have to change `History.md` and perhaps something else what I don't know.

**Comment by keithdoggett** [comment]
Yeah I'll update `History.md` and create a branch from the most recent commit before this that will still be compatible with the old dbf and ruby versions.

**Comment by keithdoggett** [comment]
Released the new version

**Comment by alvir** [comment]
Great!

**Pull request merged**
